### ISSUE TITLE
Segmentation violation during jx boot with Terraform

### ISSUE THREAD

**Issue by vincentchemouny** [jenkins-x/terraform-aws-eks-jx#19]
Using the **jenkins-x/terraform-aws-eks-jx** repo, I created a Kubernetes cluster and all the cloud resources that jx will need later (vault S3 bucket, reports S3 bucket, Dynamo DB tables etc.) for jx boot.

    terraform init
    terraform plan
    terraform apply

Terraform created all my resources and generate a "*jx-requirements.yml*" file which is already filled with the good values and the good parameters so that jx can read it on jx boot.
Then I run : 
`jx boot -r jx-requirements.yml` 

as it's said in the **README** on the repo.

**But after two seconds I got this output :**

    Stashing any changes made in local boot clone.
    Booting Jenkins X
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x36dc0f7]
    goroutine 1 [running]:
    
    github.com/jenkins-x/jx/pkg/cmd/boot.(*BootOptions).Run(0xc000639220, 0x0, 0x0)
			/workspace/source/pkg/cmd/boot/boot.go:238 +0x787
	main.main()
			/workspace/source/cmd/jx/jx.go:11 +0x32

jx, kubectl, go and terraform are installed and updated

***jx** : 2.0.1261
**kubectl** : v1.16.8
**go** : go1.13.8
**Terraform** v0.12.24*

**Comment by hferentschik** [comment]
This might actually turn out to be an issue for `jx` directly and we might need to open an issue there as well, but let's discuss here first more.

When you run `jx boot -r jx-requirements.yml`? From within a new/empty directory? Or from within the directory, you ran Terrraform from? The latter will not work. You need to run from an empty directory and copy the requirements file into it or reference the path to it (absolute or relative). 

If you execute `jx boot` from within the same directory as Terraform, it would explain why you get  the error, since the panic happens here:

```go
	for _, e := range projectConfig.PipelineConfig.Pipelines.Release.Pipeline.Environment {
		if e.Name == "DEPLOY_NAMESPACE" {
			envVars = append(envVars, v1.EnvVar{
				Name:  "DEPLOY_NAMESPACE",
				Value: requirements.Cluster.Namespace,
			})
		} else {
			envVars = append(envVars, e)
		}
	}
```

The `jx` code tries to iterate the release pipelines which we don't have in this repo.
