### ISSUE TITLE
wget command not found

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/terraform-aws-eks-jx#49]
When running `terraform apply`, there is a `local-exec` command that uses `wget`. If we do need something like that, I propose we use `curl` instead. It is installed by default almost everywhere, while `wget` is not that common. For example, macOS does have `curl`, but doesn't have `wget`.

Right now, I'm getting `module.eks-jx.module.cluster.module.eks.null_resource.wait_for_cluster[0] (local-exec): /bin/sh: wget: command not found` from `terraform apply`.

**Comment by ankitm123** [comment]
We could use the `wait_for_cluster_cmd` and use curl instead of wget. However, the problem would be that if someone uses the hashicorp terraform docker image to run terraform (may be in a CI pipeline), then this will error out, as curl is not installed in that docker image. https://github.com/terraform-aws-modules/terraform-aws-eks/issues/741
May be better to add in the read me section, that wget is a pre-req for this module, and needs to be installed? wdyt @vfarcic?

**Comment by vfarcic** [comment]
I would prefer `curl` since `wget` is rarely available by default. Nevertheless, not having it in the `terraform` image makes is a bad choice as well.

I think you're right. Making it clear that it is a pre-req is OK.

**Comment by hferentschik** [comment]
Actually, this is not an "issue" of our terraform code, but of the [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) which we use to create the actual cluster. This module has a variable to specify the `wait_for_cluster_command`. It used to be `curl`, but as of [v9.0.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v9.0.0) it's `wget`. 

So I think instead of just saying you need `wget` as a dependency, we should go a step further and expose the `wait_for_cluster_command` variable from our module as well. This way it can easily be changed if necessary. WDYT?

As @ankitm123 was pointing out the reason for the change from `wget` to `curl` was what's supported in the Hashicorp image - https://github.com/terraform-aws-modules/terraform-aws-eks/pull/750

**Comment by ankitm123** [comment]
Initially I wanted to do the same, use the `wait_for_cluster_cmd`, but I saw your PR removing it, so I was not sure, if we wanted to bring it back: https://github.com/jenkins-x/terraform-aws-eks-jx/pull/26. I am fine adding it back @hferentschik 👍
